project:
  type: website
  output-dir: docs

website:
  title: "Tokens vs. Humans: AI Sentiment and the Demand for Data Jobs"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: data.qmd
        text: "Data"
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: custom.scss
    toc: true
    toc-location: left
    fontsize: 1.05rem
    grid:
      body-width: 900px


