project:
  type: website
  output-dir: docs

website:
  title: "DSAN-AI-Project"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: data.qmd
        text: "Data"
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



